{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"name":"PyAdvanced1.4_ExceptionHandling.ipynb","provenance":[],"collapsed_sections":[]},"kernelspec":{"name":"python3","display_name":"Python 3"}},"cells":[{"cell_type":"markdown","metadata":{"id":"m8tvlceuQtAM","colab_type":"text"},"source":["## Exception\n","\n","When Python Interpreter encounters something wrong, it will raise an **exception**.\n"]},{"cell_type":"code","metadata":{"id":"0ZqPtjJ5Qm4M","colab_type":"code","colab":{}},"source":["# Executing this code will cause an exception\n","# Because the if statement must has a \":\" after the condition.\n","if a < 1\n","  print(\"The value is too small\")"],"execution_count":0,"outputs":[]},{"cell_type":"code","metadata":{"id":"RAj3rHOoSH4i","colab_type":"code","colab":{}},"source":["# This code will cause an exception as well\n","1 / 0"],"execution_count":0,"outputs":[]},{"cell_type":"code","metadata":{"id":"X9rizUGUyRvy","colab_type":"code","colab":{}},"source":["# Executing this code will cause an exception \"index out of range\"\n","b = [0, 1, 2]\n","print('b[2]=', b[2])\n","print('This should cause an exception: b[3]=', b[3])"],"execution_count":0,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"jld-briwSRI6","colab_type":"text"},"source":["### Python has many built-in exceptions\n","\n","Exception\t| Cause of Error\n","--- | ---\n","AssertionError|\tRaised when assert statement fails.\n","AttributeError|\tRaised when attribute assignment or reference fails.\n","EOFError|\tRaised when the input() functions hits end-of-file condition.\n","FloatingPointError|\tRaised when a floating point operation fails.\n","GeneratorExit|\tRaise when a generator's close() method is called.\n","ImportError|\tRaised when the imported module is not found.\n","IndexError|\tRaised when index of a sequence is out of range.\n","KeyError|\tRaised when a key is not found in a dictionary.\n","KeyboardInterrupt|\tRaised when the user hits interrupt key (Ctrl+c or delete).\n","MemoryError|\tRaised when an operation runs out of memory.\n","NameError|\tRaised when a variable is not found in local or global scope.\n","NotImplementedError|\tRaised by abstract methods.\n","OSError|\tRaised when system operation causes system related error.\n","OverflowError|\tRaised when result of an arithmetic operation is too large to be represented.\n","ReferenceError|\tRaised when a weak reference proxy is used to access a garbage collected referent.\n","RuntimeError|\tRaised when an error does not fall under any other category.\n","StopIteration|\tRaised by next() function to indicate that there is no further item to be returned by iterator.\n","SyntaxError|\tRaised by parser when syntax error is encountered.\n","IndentationError|\tRaised when there is incorrect indentation.\n","TabError|\tRaised when indentation consists of inconsistent tabs and spaces.\n","SystemError|\tRaised when interpreter detects internal error.\n","SystemExit|\tRaised by sys.exit() function.\n","TypeError|\tRaised when a function or operation is applied to an object of incorrect type.\n","UnboundLocalError|\tRaised when a reference is made to a local variable in a function or method, but no value has been bound to that variable.\n","UnicodeError|\tRaised when a Unicode-related encoding or decoding error occurs.\n","UnicodeEncodeError|\tRaised when a Unicode-related error occurs during encoding.\n","UnicodeDecodeError|\tRaised when a Unicode-related error occurs during decoding.\n","UnicodeTranslateError|\tRaised when a Unicode-related error occurs during translating.\n","ValueError|\tRaised when a function gets argument of correct type but improper value.\n","ZeroDivisionError|\tRaised when second operand of division or modulo operation is zero.\n","\n","A user can also define his/her own exceptions."]},{"cell_type":"markdown","metadata":{"id":"VS1xX58TTIVI","colab_type":"text"},"source":["## Exception handling\n","\n","When an exception occurs, it causes the current process to stop and **pass the exception** to the calling process until it is handled. \n","\n","* For example, if function A calls function B which in turn calls function C and an exception occurs in function C. If C does not handle the exception, the exception is passed to B and then to A.\n","* If never handled, an error message is spit out and our program come to a unexpected halt.\n","\n","What do we mean by \"pass an exception\"?\n","* An exception is actually an exception object of the exception class.\n","* When an exception occurs, the current process stops, creates an exception object, and passes that exception object to the calling process. "]},{"cell_type":"markdown","metadata":{"id":"A_jLnRYpTyA4","colab_type":"text"},"source":["### The try statement\n","In Python, the exceptions are handled by the \"try\" statement.\n","\n","A try statement \n","* Always has a try: block.  The try block always gets executed\n","* Always has a except: block.  The except block gets executed when an exception ocurrs\n","* Optionally has a finally: block.  When exist, the finally block always gets executed."]},{"cell_type":"code","metadata":{"id":"OFrTxRXbT5c5","colab_type":"code","colab":{}},"source":["# import module sys to get the type of exception\n","import sys\n","\n","random_list = ['a', 0, 2]\n","\n","def cal_reciprocal(entry):\n","  try:\n","    print(\"The entry is\", entry)\n","    r = 1/int(entry)\n","    return r\n","  except:\n","    print(\"Oops!\", sys.exc_info()[0], \"occured.\")\n","    print(\"Next entry.\")\n","    return \"Undefined\"\n","\n","# if we do not use the try statement in the function, \n","# the execution will end at the first entry of the random_list\n","for i in random_list:\n","  r = cal_reciprocal(i)\n","  print(\"The reciprocal of\",i,\"is\",r)\n","  print()"],"execution_count":0,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"xubQSe872ieF","colab_type":"text"},"source":["## How to obtain the name exception in runtime?\n","In the example above, we get the name of Exception by calling `sys.exc_info()[0]`.  There are several ways:\n","\n","1. Call sys.exc_infro(): this function returns a tuple `(type, value, traceback)` where `type` is the type (class name) of the exception.  `Value` is the argument we passed in when we `raise` the exception.  `traceback` is the traceback information.\n","\n","2. We use the phase `except Exception as excetion` to catch the exception. In this case, the exception object will be assigned to the `exception` variable.  Then we can get the class of the object , and then get the class name from the class, as follows:\n","  1. `exception.__class__.__name__`, or\n","  2. `type(exception).__name__`"]},{"cell_type":"code","metadata":{"id":"tXQpwZTV4EU3","colab_type":"code","outputId":"d67d286c-4502-4df9-f7db-29fddbf6d99d","executionInfo":{"status":"ok","timestamp":1590494792150,"user_tz":-480,"elapsed":1434,"user":{"displayName":"ML Lo","photoUrl":"","userId":"11511065297651515564"}},"colab":{"base_uri":"https://localhost:8080/","height":151}},"source":["help(sys.exc_info)"],"execution_count":0,"outputs":[{"output_type":"stream","text":["Help on built-in function exc_info in module sys:\n","\n","exc_info(...)\n","    exc_info() -> (type, value, traceback)\n","    \n","    Return information about the most recent exception caught by an except\n","    clause in the current stack frame or in an older stack frame.\n","\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"vLcBSlGS3Bm_","colab_type":"code","outputId":"0d3ce755-5890-4d28-9e78-2a87bfae7613","executionInfo":{"status":"ok","timestamp":1590494703688,"user_tz":-480,"elapsed":1315,"user":{"displayName":"ML Lo","photoUrl":"","userId":"11511065297651515564"}},"colab":{"base_uri":"https://localhost:8080/","height":235}},"source":["import sys\n","random_list = ['a', 0, 2]\n","\n","def cal_reciprocal(entry):\n","  try:\n","    print(\"The entry is\", entry)\n","    r = 1/int(entry)\n","    return r\n","  except Exception as exception:\n","    #print(\"Oops!\", sys.exc_info()[0], \"occured.\")\n","    print(\"Oops!\", exception.__class__.__name__, \"occured\")\n","    #print(\"Oops!\", type(exception).__name__, \"occured\")\n","    print(\"Next entry.\")\n","    return \"Undefined\"\n","\n","# if we do not use the try statement in the function, \n","# the execution will end at the first entry of the random_list\n","for i in random_list:\n","  r = cal_reciprocal(i)\n","  print(\"The reciprocal of\",i,\"is\",r)\n","  print()"],"execution_count":0,"outputs":[{"output_type":"stream","text":["The entry is a\n","Oops! ValueError occured\n","Next entry.\n","The reciprocal of a is Undefined\n","\n","The entry is 0\n","Oops! ZeroDivisionError occured\n","Next entry.\n","The reciprocal of 0 is Undefined\n","\n","The entry is 2\n","The reciprocal of 2 is 0.5\n","\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"fKpGDqhR7SST","colab_type":"text"},"source":["## Structure of the try compound statement.\n","* Try: block (must have)\n","* except: block (must have)\n","* else: block (option)\n","* finally: block (option)"]},{"cell_type":"code","metadata":{"id":"tdNJcWohWV8y","colab_type":"code","colab":{}},"source":["# get_reciprocal()  version2\n","# Add a finally: block that will always be executed, whether or not there is an exception\n","random_list = ['a', 0, 2]\n","\n","def get_reciprocal(entry):\n","  try:\n","    print(\"The entry is\", entry)\n","    r = 1/int(entry)\n","  except:\n","    print(\"Oops!\",sys.exc_info()[0],\"occured.\")\n","    print(\"Next entry.\")\n","    r = \"Undefined\"\n","  finally:\n","    print(\"Finishing processing of {}\".format(entry))\n","    return r\n","\n","# if we do not use the try statement in the function, \n","# the execution will end at the first entry of the random_list\n","for i in random_list:\n","  r = get_reciprocal(i)\n","  print(\"The reciprocal of {} is {}--------\".format(i, r))\n","  print()"],"execution_count":0,"outputs":[]},{"cell_type":"code","metadata":{"colab_type":"code","id":"oAk53xKV609r","outputId":"66e98ad9-fbaa-4b41-969e-bb5a3355745b","executionInfo":{"status":"ok","timestamp":1590495573152,"user_tz":-480,"elapsed":1215,"user":{"displayName":"ML Lo","photoUrl":"","userId":"11511065297651515564"}},"colab":{"base_uri":"https://localhost:8080/","height":302}},"source":["# get_reciprocal()  version3\n","# Add an else: block, which will be executed if no exception ocurrs\n","random_list = ['a', 0, 2]\n","\n","def get_reciprocal(entry):\n","  try:\n","    print(\"The entry is\", entry)\n","    r = 1/int(entry)\n","  except:\n","    print(\"Oops!\",sys.exc_info()[0],\"occured.\")\n","    print(\"Next entry.\")\n","    r = \"Undefined\"\n","  else:\n","    print(\"No exception! Everything is good.\")\n","  finally:\n","    print(\"Finishing processing of {}\".format(entry))\n","    return r\n","\n","# if we do not use the try statement in the function, \n","# the execution will end at the first entry of the random_list\n","for i in random_list:\n","  r = get_reciprocal(i)\n","  print(\"The reciprocal of {} is {}--------\".format(i, r))\n","  print()"],"execution_count":0,"outputs":[{"output_type":"stream","text":["The entry is a\n","Oops! <class 'ValueError'> occured.\n","Next entry.\n","Finishing processing of a\n","The reciprocal of a is Undefined--------\n","\n","The entry is 0\n","Oops! <class 'ZeroDivisionError'> occured.\n","Next entry.\n","Finishing processing of 0\n","The reciprocal of 0 is Undefined--------\n","\n","The entry is 2\n","No exception!  Everything is good.\n","Finishing processing of 2\n","The reciprocal of 2 is 0.5--------\n","\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"6Rb9RnCtXKrK","colab_type":"text"},"source":["### Process specific exceptions \n","\n","You can process different types of exceptions differently with multiple `except: blocks.  All such `except:` blocks except one must have an exception name.\n","\n"]},{"cell_type":"code","metadata":{"id":"0t4CCqS0Yg8b","colab_type":"code","outputId":"3dd22b9f-683c-418f-e746-afedff1b8265","executionInfo":{"status":"ok","timestamp":1590494239863,"user_tz":-480,"elapsed":1253,"user":{"displayName":"ML Lo","photoUrl":"","userId":"11511065297651515564"}},"colab":{"base_uri":"https://localhost:8080/","height":269}},"source":["import sys\n","\n","# get_reciprocal()  version3\n","# using the raise statement\n","random_list = ['a', 0, 2]\n","\n","def get_reciprocal(entry):\n","  try:\n","    print(\"The entry is\", entry)\n","    r = 1/int(entry)\n","  except ZeroDivisionError:\n","    print(\"You cannot divied by Zero!\", sys.exc_info()[0],\"occured.\")\n","    r = \"DivByZero Error\"\n","  except:\n","    print(\"Oops!\", sys.exc_info()[0], \"occured.\")\n","    r = \"Undefined\"\n","  else:\n","    print(\"No exception encountered\")\n","  finally:\n","    print(\"Finishing processing of {}\".format(entry))\n","    return r\n","\n","# if we do not use the try statement in the function, \n","# the execution will end at the first entry of the random_list\n","for i in random_list:\n","  r = get_reciprocal(i)\n","  print(\"The reciprocal of {} is {}--------\".format(i, r))\n","  print()"],"execution_count":0,"outputs":[{"output_type":"stream","text":["The entry is a\n","Oops! <class 'ValueError'> occured.\n","Finishing processing of a\n","The reciprocal of a is Undefined--------\n","\n","The entry is 0\n","You cannot divied by Zero! <class 'ZeroDivisionError'> occured.\n","Finishing processing of 0\n","The reciprocal of 0 is DivByZero Error--------\n","\n","The entry is 2\n","No exception encountered\n","Finishing processing of 2\n","The reciprocal of 2 is 0.5--------\n","\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"rigK5wm2Yq8d","colab_type":"text"},"source":["## User can raise exception\n","\n","In addition to the exception raised by the system, the user can raise exceptions to handle programming violations.  \n","\n","When the user raises an exception, he can pass additional information as the arguments of the exception.  Such information is available as `exception.args` in the `except:` block.\n","\n","You can passed in as many arguments as you need when you raise an exception."]},{"cell_type":"code","metadata":{"id":"UMgSM6xUXapE","colab_type":"code","outputId":"b0a7fa58-dc50-42cb-d09c-48f42da35468","executionInfo":{"status":"ok","timestamp":1590496305907,"user_tz":-480,"elapsed":1885,"user":{"displayName":"ML Lo","photoUrl":"","userId":"11511065297651515564"}},"colab":{"base_uri":"https://localhost:8080/","height":353}},"source":["# get_reciprocal()  version4\n","random_list = ['a', 0, -3.5, 2]\n","\n","def get_reciprocal(entry):\n","  try:\n","    print(\"The entry is\", entry)\n","    if entry < 0:\n","      raise ValueError(entry)    # <== user raise exception explicitly\n","    r = 1/int(entry)\n","  except ZeroDivisionError:\n","    print(\"You cannot divied by Zero!\", sys.exc_info()[0],\"occured.\")\n","    r = \"DivByZero Error\"\n","  except ValueError as e:\n","    print(\"We don't like negative values!\", sys.exc_info()[0],\"occured.\")\n","    print(\"The value we don't like is:\", e.args[0])\n","    r = \"Rejected\"\n","  except:\n","    print(\"Oops!\",sys.exc_info()[0],\"occured.\")\n","    r = \"Undefined\"\n","  finally:\n","    print(\"Finishing processing of {}\".format(entry))\n","    return r\n","\n","# if we do not use the try statement in the function, \n","# the execution will end at the first entry of the random_list\n","for i in random_list:\n","  r = get_reciprocal(i)\n","  print(\"The reciprocal of {} is {}--------\".format(i, r))\n","  print()"],"execution_count":0,"outputs":[{"output_type":"stream","text":["The entry is a\n","Oops! <class 'TypeError'> occured.\n","Finishing processing of a\n","The reciprocal of a is Undefined--------\n","\n","The entry is 0\n","You cannot divied by Zero! <class 'ZeroDivisionError'> occured.\n","Finishing processing of 0\n","The reciprocal of 0 is DivByZero Error--------\n","\n","The entry is -3.5\n","We don't like negative values! <class 'ValueError'> occured.\n","The value we don't like is: -3.5\n","Finishing processing of -3.5\n","The reciprocal of -3.5 is Rejected--------\n","\n","The entry is 2\n","Finishing processing of 2\n","The reciprocal of 2 is 0.5--------\n","\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"TVW42qesZqZY","colab_type":"text"},"source":["## User defined exceptions\n","\n","Users can define the users' own exceptions \n","* By creating a new class. \n","* User defined exception class must be derived directly or indirectly from the built-in **Exception class**. \n","* Most of the built-in exceptions are also derived form this class."]},{"cell_type":"code","metadata":{"id":"J_sCXHYkaBYB","colab_type":"code","outputId":"ea3f5248-3b60-4c66-a383-fb56e70439d9","executionInfo":{"status":"ok","timestamp":1590497327162,"user_tz":-480,"elapsed":1247,"user":{"displayName":"ML Lo","photoUrl":"","userId":"11511065297651515564"}},"colab":{"base_uri":"https://localhost:8080/","height":521}},"source":["# Defined our own exception here\n","class ValueDislikeException(Exception):\n","   \"\"\"Raised when the input value is something we don't like\"\"\"\n","   pass\n","class BadNameException(Exception):\n","   \"\"\"Raised when the input value is a forbidden name\"\"\"\n","   pass\n","\n","\n","# get_reciprocal()  version5\n","def get_reciprocal(entry):\n","  badname_list = ['Dog', 'Cat', 'Mouse']\n","  dislikenum_list = [13, 16, 19]\n","\n","  try:\n","    print(\"The entry is\", entry)\n","    if entry in badname_list:\n","      raise BadNameException(entry)\n","    elif entry < 0:\n","      raise ValueError(entry)    \n","    elif entry in dislikenum_list:\n","      raise ValueDislikeException(entry)\n","    else:\n","      pass\n","    r = 1/int(entry)\n","  except ZeroDivisionError:\n","    print(\"You cannot divied by Zero!\", sys.exc_info()[0],\"occured.\")\n","    r = \"DivByZero Error\"\n","  except ValueError as e:\n","    print(\"We don't like this negative values:\", e.args[0])\n","    print(sys.exc_info()[0],\"occured.\")\n","    r = \"Rejected\"\n","  except Exception as e:\n","    print(\"Oops!\",sys.exc_info()[0],\"occured.\")\n","    r = \"Undefined\"\n","  finally:\n","    print(\"Finishing processing of {}\".format(entry))\n","    return r\n","\n","# if we do not use the try statement in the function, \n","# the execution will end at the first entry of the random_list\n","random_list = ['a', 0, -3.5, 'Dog', 13, 2]\n","for i in random_list:\n","  r = get_reciprocal(i)\n","  print(\"The reciprocal of {} is {}--------\".format(i, r))\n","  print()\n"],"execution_count":0,"outputs":[{"output_type":"stream","text":["The entry is a\n","Oops! <class 'TypeError'> occured.\n","Finishing processing of a\n","The reciprocal of a is Undefined--------\n","\n","The entry is 0\n","You cannot divied by Zero! <class 'ZeroDivisionError'> occured.\n","Finishing processing of 0\n","The reciprocal of 0 is DivByZero Error--------\n","\n","The entry is -3.5\n","We don't like this negative values: -3.5\n","<class 'ValueError'> occured.\n","Finishing processing of -3.5\n","The reciprocal of -3.5 is Rejected--------\n","\n","The entry is Dog\n","Oops! <class '__main__.BadNameException'> occured.\n","Finishing processing of Dog\n","The reciprocal of Dog is Undefined--------\n","\n","The entry is 13\n","Oops! <class '__main__.ValueDislikeException'> occured.\n","Finishing processing of 13\n","The reciprocal of 13 is Undefined--------\n","\n","The entry is 2\n","Finishing processing of 2\n","The reciprocal of 2 is 0.5--------\n","\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"X_29S_BYLkjz","colab_type":"text"},"source":["## What can be raised? (Advaneced topic)\n","Previously we defined our own exception by defining a new name for the new exception.  But actually we can do more to custome-make an exception. A class can be raised as an exception as long as it satifies the following three conditions:\n","* It inherits the **BaseException** class\n","* It implements the `__init__()` method.  \n","  * This method will be called by the system to create a new exception object when the raise command is encountered.\n","* It implements the `__str__()` method.\n","  * This method will be called by the system to print out a message (after the exception object is created) as part of the the default exception handling, when the exception is not catched by the `except` block.\n","  * If the except is catched by the `except:` block, the statement in the block will be executed, and the `__str__()` method will not be executed. \n","\n","These are really minimalist requirements."]},{"cell_type":"code","metadata":{"id":"NDgC9qIdLkFD","colab_type":"code","outputId":"f45d9c5f-fe45-4094-c5eb-9c70e0db6618","executionInfo":{"status":"error","timestamp":1590552485252,"user_tz":-480,"elapsed":1226,"user":{"displayName":"ML Lo","photoUrl":"","userId":"11511065297651515564"}},"colab":{"base_uri":"https://localhost:8080/","height":282}},"source":["class MinimalistException(BaseException):\n","  def __init__(self, *args):\n","    if args:\n","      self.message = args[0]\n","    else:\n","      self.message = None\n","  def __str__(self):\n","    print('calling str')\n","    if self.message:\n","      return self.__class__.__name__ + ' - ' +self.message\n","    else:\n","      return self.__class__.__name__ + 'has been raised'\n","\n","print('Note when we raise the exception, whatever implemented in the __str__() method will be sent to print')\n","raise MinimalistException('Experimenting with exception')"],"execution_count":0,"outputs":[{"output_type":"stream","text":["Note when we raise the exception, whatever implemented in the __str__() method will be sent to print\n","calling str\n"],"name":"stdout"},{"output_type":"error","ename":"MinimalistException","evalue":"ignored","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mMinimalistException\u001b[0m                       Traceback (most recent call last)","\u001b[0;32m<ipython-input-31-8da081a063a8>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[1;32m     13\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     14\u001b[0m \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'Note when we raise the exception, whatever implemented in the __str__() method will be sent to print'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 15\u001b[0;31m \u001b[0;32mraise\u001b[0m \u001b[0mMinimalistException\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'Experimenting with exception'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;31mMinimalistException\u001b[0m: MinimalistException - Experimenting with exception"]},{"output_type":"stream","text":["calling str\n","calling str\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"mA-xzHe0PitX","colab_type":"code","outputId":"c98c2c9b-8fae-4aa6-e845-724775c6fcdc","executionInfo":{"status":"ok","timestamp":1590552550276,"user_tz":-480,"elapsed":1342,"user":{"displayName":"ML Lo","photoUrl":"","userId":"11511065297651515564"}},"colab":{"base_uri":"https://localhost:8080/","height":84}},"source":["try:\n","  print('Execute something here')\n","  raise MinimalistException\n","except BaseException as e:\n","  print('Handle exceptions here')\n","  print('This is a', e.__class__.__name__)\n","finally:\n","  print('Do something at the end')"],"execution_count":0,"outputs":[{"output_type":"stream","text":["Execute something here\n","Handle exceptions here\n","This is a MinimalistException\n","Do something at the end\n"],"name":"stdout"}]}]}